INSERT INTO jurisdiction_config(jurisdiction_id,configuration_id,value,comment)
VALUES (1,1,'True',''),
       (1,2,'Null',''),
       (1,3,'True',''),
       (2,1,'True',''),
       (2,2,'100',''),
       (2,3,'True',''),
       (3,1,'False',''),
       (3,2,'False','New regulation starts in Sep/2020'),
       (3,3,'False',''),
       (4,1,'True',''),
       (4,2,'20',''),
       (4,3,'False',''),
       (5,1,'True',''),
       (5,2,'50','Value will be changed in July/2020'),
       (5,3,'False','');